- name: Install Packages
  hosts: all
  become: yes
  tasks:
  - name: Install nano editor
    ansible.builtin.dnf:
      name: nano
      state: present
  
  - name: Install Ansible
    ansible.builtin.dnf:
      name: ansible
      state: present
  
  - name: Install Python3
    ansible.builtin.dnf:
      name: python3
      state: present
  
  - name: Install Python3 pip
    ansible.builtin.dnf:
      name: python3-pip
      state: present
  
  - name: Install boto3
    ansible.builtin.pip:
      name: boto3
      state: present
  
  - name: Install botocore
    ansible.builtin.pip:
      name: botocore
      state: present
  
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: Start Nginx service
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes