- name: Delete app Directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  #ignore_errors: yes

- name: Create app Directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: Download and Expreact Code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes