- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_config_check
  changed_when: false
  failed_when: nginx_config_check.rc != 0

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes